next step

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,12 +1,30 @@
 pipeline {
-  agent {
-    label 'jenkins_agent_portfolio'
-  }
+  agent none
   stages {
     stage ('Build') {
       steps {
-        echo "testing agent creation"
+        echo "Initializing Project Build"
+        sh "docker build -t portfolio-image ."
+        echo "Build Successful"
       }
+    }
+    stage ('Deploy') {
+      steps {
+        echo "Initializing Project Deploy"
+        sh '''
+          docker-compose -f /home/jenkins/agent/workspace/my_server_pipeline_master/docker-compose.yml down || true
+            docker-compose -f /home/jenkins/agent/workspace/my_server_pipeline_master/docker-compose.yml up -d
+          '''
+        echo "Deploy Successful"
+      }
+    }
+  }
+  post {
+    success {
+      echo "Pipeline completed successfully!"
+    }
+    failure {
+      echo "Pipeline failed. Check the logs for details."
     }
   }
 }
